// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  version: env['npm_package_version'],
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  redirect_uri: '/InternProject/token',
  client_id: '47edf49c144940739a4f77370816d781',
  client_secret: '574cddd4efe54fae852b66a549a76bd3',
  supportedLanguages: ['en-US', 'fr-FR'],
};
